import { UserProfile, Trip, TimelineChapter, VisitedPlace, WishlistItem } from '@/types';

export const MOCK_USER: UserProfile = {
  id: 'user_alex_gourmet',
  username: 'alex_gourmet',
  displayName: 'Alex Rivers',
  bio: 'Culinary explorer & food photojournalist traveling the globe one bowl of ramen at a time. 🍜✨',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
  favoriteCuisines: ['Japanese', 'Italian', 'Vietnamese', 'Oaxacan'],
  location: 'San Francisco & Tokyo',
  joinedDate: '2024-01-15',
};

export const MOCK_TRIPS: Trip[] = [
  {
    id: 'trip_tokyo_2025',
    userId: 'user_alex_gourmet',
    title: 'Tokyo Ramen & Sushi Odyssey',
    slug: 'tokyo-ramen-odyssey',
    destination: 'Tokyo, Japan',
    startDate: '2025-04-10',
    endDate: '2025-04-14',
    coverUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80',
    summary: 'A 5-day deep dive through Shinjuku izakayas, Tsukiji outer market omakase, Ginza Michelin-starred ramen, and hidden Shibuya kissaten back-alleys.',
    visibility: 'public',
    createdAt: '2025-04-09T10:00:00Z',
  },
  {
    id: 'trip_tuscany_2024',
    userId: 'user_alex_gourmet',
    title: 'Tuscan Pasta & Truffle Trail',
    slug: 'tuscan-pasta-trail',
    destination: 'Florence & Chianti, Italy',
    startDate: '2024-09-18',
    endDate: '2024-09-22',
    coverUrl: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80',
    summary: 'Hand-rolled pici, fresh black truffle tagliolini, Chianti Classico vineyard tastings, and artisan gelato in San Gimignano.',
    visibility: 'public',
    createdAt: '2024-09-17T14:30:00Z',
  },
];

export const MOCK_CHAPTERS: Record<string, TimelineChapter[]> = {
  trip_tokyo_2025: [
    {
      id: 'chap_tokyo_d1',
      tripId: 'trip_tokyo_2025',
      dayNumber: 1,
      date: '2025-04-10',
      title: 'Day 1: Shinjuku Neon & Midnight Tonkotsu',
      notes: 'Landed at Haneda, dropped bags at Hotel Gracery, and went straight to Omoide Yokocho and Fuunji.',
    },
    {
      id: 'chap_tokyo_d2',
      tripId: 'trip_tokyo_2025',
      dayNumber: 2,
      date: '2025-04-11',
      title: 'Day 2: Tsukiji Dawn & Ginza Michelin Craft',
      notes: 'Woke up early for fresh sea urchin and tamagoyaki at Tsukiji, followed by an unforgettable bowl at Nakajima.',
    },
    {
      id: 'chap_tokyo_d3',
      tripId: 'trip_tokyo_2025',
      dayNumber: 3,
      date: '2025-04-12',
      title: 'Day 3: Shibuya Coffee & Roppongi Wagyu Sizzle',
      notes: 'Artisanal pour-overs in Yoyogi Park, vinyl coffee shops, and high-end teppanyaki.',
    },
  ],
  trip_tuscany_2024: [
    {
      id: 'chap_tuscany_d1',
      tripId: 'trip_tuscany_2024',
      dayNumber: 1,
      date: '2024-09-18',
      title: 'Day 1: Mercato Centrale & Bistecca alla Fiorentina',
      notes: 'Exploring the heart of Florence and trying authentic Florentine steak.',
    },
    {
      id: 'chap_tuscany_d2',
      tripId: 'trip_tuscany_2024',
      dayNumber: 2,
      date: '2024-09-19',
      title: 'Day 2: Chianti Hills & Fresh Truffle Pasta',
      notes: 'Driving through vineyards and enjoying shaved black truffle tagliolini in Greve.',
    },
  ],
};

export const MOCK_VISITED_PLACES: Record<string, VisitedPlace[]> = {
  trip_tokyo_2025: [
    {
      id: 'vp_fuunji',
      tripId: 'trip_tokyo_2025',
      chapterId: 'chap_tokyo_d1',
      placeId: 'ChIJa18R4QeMGGARmE5yvYV61hM',
      name: 'Fuunji (風雲児)',
      address: '2-14-3 Yoyogi, Shibuya-ku, Tokyo',
      lat: 35.6875,
      lng: 139.6972,
      visitTime: '2025-04-10T19:30:00Z',
      photoUrls: [
        'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1591814468924-caf88d1232e1?auto=format&fit=crop&w=800&q=80',
      ],
      dishTags: ['Tsukemen', 'Rich Fish Powder Dip', 'Ajitama Egg', 'Chashu Pork'],
      rating: 5,
      tastingNotes: 'The ultimate dipping ramen in Tokyo! Creamy poultry-fish broth with an intense umami bomb of bonito powder. Perfectly chewy thick noodles.',
      priceLevel: 2,
      category: 'Ramen',
      recommendedDish: 'Special Tsukemen (つけめん)',
    },
    {
      id: 'vp_torishige',
      tripId: 'trip_tokyo_2025',
      chapterId: 'chap_tokyo_d1',
      placeId: 'ChIJ5c3VpAeMGGARaL54_qWqCVM',
      name: 'Torishige (鳥茂)',
      address: '2-6-5 Yoyogi, Shibuya-ku, Tokyo',
      lat: 35.6882,
      lng: 139.6991,
      visitTime: '2025-04-10T21:45:00Z',
      photoUrls: [
        'https://images.unsplash.com/photo-1555126634-323283e090fa?auto=format&fit=crop&w=800&q=80',
      ],
      dishTags: ['Yakitori', 'Stuffed Skewers', 'Charcoal Grill', 'Sake'],
      rating: 5,
      tastingNotes: 'Historic yakitori spot operating since 1949. Charcoal smoky perfection, especially the minced pork & green pepper skewered delight.',
      priceLevel: 3,
      category: 'Izakaya',
      recommendedDish: 'Pork Tsukune & Stuffed Peppers',
    },
    {
      id: 'vp_tsukiji_sushi',
      tripId: 'trip_tokyo_2025',
      chapterId: 'chap_tokyo_d2',
      placeId: 'ChIJ1X2tBAyLGGARyRkF-LgC0oM',
      name: 'Tsukiji Kagura Sushi',
      address: '4-14-13 Tsukiji, Chuo-ku, Tokyo',
      lat: 35.6654,
      lng: 139.7706,
      visitTime: '2025-04-11T08:15:00Z',
      photoUrls: [
        'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1611143669185-af224c5e3252?auto=format&fit=crop&w=800&q=80',
      ],
      dishTags: ['Otoro Nigiri', 'Hokkaido Uni', 'Aburi Fatty Tuna', 'Red Vinegar Shari'],
      rating: 5,
      tastingNotes: 'Red vinegar (Akazu) seasoned rice paired with melt-in-your-mouth Otoro. The freshness at Tsukiji outer market is incomparable.',
      priceLevel: 3,
      category: 'Sushi',
      recommendedDish: 'Chef Choice Aburi Nigiri Set',
    },
    {
      id: 'vp_ginza_nakajima',
      tripId: 'trip_tokyo_2025',
      chapterId: 'chap_tokyo_d2',
      placeId: 'ChIJXQ4h_QyLGGAR9G6Z9M4n0kA',
      name: 'Shinjuku Kappo Nakajima',
      address: '3-32-5 Shinjuku, Shinjuku-ku, Tokyo',
      lat: 35.6901,
      lng: 139.7042,
      visitTime: '2025-04-11T12:30:00Z',
      photoUrls: [
        'https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=800&q=80',
      ],
      dishTags: ['Iwashi Deep Fried Sardines', 'Sesame Sauce Sashimi', 'Michelin Star Lunch'],
      rating: 4,
      tastingNotes: 'Incredible value Michelin star lunch set featuring fresh sardine sesame sashimi and crispy panko deep fried sardines.',
      priceLevel: 2,
      category: 'Kaiseki',
      recommendedDish: 'Iwashi Furai Set',
    },
    {
      id: 'vp_about_life_coffee',
      tripId: 'trip_tokyo_2025',
      chapterId: 'chap_tokyo_d3',
      placeId: 'ChIJb6tZqAiMGGARXbWp_oWqDMM',
      name: 'About Life Coffee Brewers',
      address: '1-19-8 Dogenzaka, Shibuya-ku, Tokyo',
      lat: 35.6582,
      lng: 139.6975,
      visitTime: '2025-04-12T09:45:00Z',
      photoUrls: [
        'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
      ],
      dishTags: ['Single Origin Ethiopian Pour-over', 'Matcha Latte', 'Artisan Coffee'],
      rating: 4,
      tastingNotes: 'Crisp floral single origin pour-over coffee served from a minimalist corner standing booth in Shibuya.',
      priceLevel: 1,
      category: 'Café',
      recommendedDish: 'Ethiopia Guji Filter Coffee',
    },
    {
      id: 'vp_yakiniku_jumbo',
      tripId: 'trip_tokyo_2025',
      chapterId: 'chap_tokyo_d3',
      placeId: 'ChIJd_6RPAyLGGARM2tF81q1YvE',
      name: 'Yakiniku Jumbo Hanare',
      address: '3-27-7 Hongo, Bunkyo-ku, Tokyo',
      lat: 35.7065,
      lng: 139.7612,
      visitTime: '2025-04-12T19:00:00Z',
      photoUrls: [
        'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
      ],
      dishTags: ['A5 Kuroge Wagyu', 'Nohara Yaki', 'Egg Yolk Dip', 'Charcoal Yakiniku'],
      rating: 5,
      tastingNotes: 'Thinly sliced A5 Wagyu sirloin seared for 4 seconds on charcoal, then dipped in raw egg yolk. Pure luxury.',
      priceLevel: 4,
      category: 'Yakiniku',
      recommendedDish: 'Nohara Yaki (野原焼き)',
    },
  ],
  trip_tuscany_2024: [
    {
      id: 'vp_all_antico',
      tripId: 'trip_tuscany_2024',
      chapterId: 'chap_tuscany_d1',
      placeId: 'ChIJ_6tZqAiMGGARXbWp_oWqDMM',
      name: "All'Antico Vinaio",
      address: 'Via dei Neri 65r, Florence, Italy',
      lat: 43.7683,
      lng: 11.2582,
      visitTime: '2024-09-18T13:00:00Z',
      photoUrls: [
        'https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=800&q=80',
      ],
      dishTags: ['Schiacciata', 'Truffle Cream', 'Prosciutto di Parma', 'Pistachio Spread'],
      rating: 5,
      tastingNotes: 'Massive Florentine focaccia sandwich overflowing with creamy stracciatella, fresh truffle cream, and paper-thin prosciutto.',
      priceLevel: 1,
      category: 'Street Food',
      recommendedDish: 'La Favolosa Sandwich',
    },
  ],
};

export const MOCK_WISHLIST: WishlistItem[] = [
  {
    id: 'wish_rokurinsha',
    userId: 'user_alex_gourmet',
    tripId: 'trip_tokyo_2025',
    placeId: 'ChIJW3PZ4QeMGGARmE5yvYV61hM',
    name: 'Rokurinsha (六厘舎)',
    address: 'Tokyo Station Ramen Street, B1F, Chiyoda-ku, Tokyo',
    lat: 35.6812,
    lng: 139.7671,
    notes: 'Legendary breakfast tsukemen! Need to arrive before 7:30 AM to avoid 1-hour queues.',
    category: 'Ramen',
    priority: 'must-try',
    createdAt: '2025-04-05T12:00:00Z',
    photoUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'wish_sukiyabashi',
    userId: 'user_alex_gourmet',
    tripId: 'trip_tokyo_2025',
    placeId: 'ChIJ5w4h_QyLGGAR9G6Z9M4n0kA',
    name: 'Sushi Sawada (鮨 さわ田)',
    address: '5-9-19 Ginza, Chuo-ku, Tokyo',
    lat: 35.6715,
    lng: 139.7638,
    notes: '6-seat intimate omakase with Master Sawada. Book 2 months in advance.',
    category: 'Sushi',
    priority: 'must-try',
    createdAt: '2025-04-06T15:30:00Z',
    photoUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'wish_kappo_ryokan',
    userId: 'user_alex_gourmet',
    tripId: 'trip_tokyo_2025',
    placeId: 'ChIJd_6RPAyLGGARM2tF81q1YvF',
    name: 'Chancery Shabu-Shabu Seryna',
      address: '3-12-2 Roppongi, Minato-ku, Tokyo',
    lat: 35.6628,
    lng: 139.7331,
    notes: 'Kobe beef shabu-shabu & sesame sauce in Roppongi.',
    category: 'Fine Dining',
    priority: 'if-time',
    createdAt: '2025-04-07T09:15:00Z',
    photoUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=400&q=80',
  },
];
