'use client';

import React, { useState, useEffect } from 'react';
import Image from 'next/image';
import { Trip, TimelineChapter, VisitedPlace, WishlistItem, AIProcessedPhotoGroup, ReelData, DecodedDish, ItineraryDay } from '@/types';
import { Navbar } from '@/components/Navbar';
import { MobileNavigation } from '@/components/MobileNavigation';
import { MapView } from '@/components/Dashboard/MapView';
import { TimelineView } from '@/components/Dashboard/TimelineView';
import { PhotoUploader } from '@/components/Dashboard/PhotoUploader';
import { WishlistDrawer } from '@/components/Dashboard/WishlistDrawer';
import { AddVisitModal } from '@/components/Dashboard/AddVisitModal';
import { CreateTripModal } from '@/components/Dashboard/CreateTripModal';
import { AuthModal } from '@/components/Auth/AuthModal';
import { OccasionPromptModal } from '@/components/Reel/OccasionPromptModal';
import { ReelViewer } from '@/components/Reel/ReelViewer';

import { MenuScannerModal } from '@/components/ai/MenuScannerModal';
import { ItineraryPlanner } from '@/components/ai/ItineraryPlanner';
import { VisualDishFinder } from '@/components/ai/VisualDishFinder';
import { SocialCaptionModal } from '@/components/ai/SocialCaptionModal';
import { subscribeToAuthChanges, logoutUser } from '@/lib/firebase/auth';
import {
  fetchUserDataFromFirestore,
  saveTripToFirestore,
  saveChapterToFirestore,
  saveVisitedPlaceToFirestore,
  deleteVisitedPlaceFromFirestore,
  saveWishlistItemToFirestore,
  deleteWishlistItemFromFirestore,
  syncUserProfileToFirestore,
} from '@/lib/firebase/firestoreData';
import { User as FirebaseUser } from 'firebase/auth';
import { Compass, MapPin, Calendar, Heart, Plus, Sparkles, Utensils, BookOpen, Share2, Layers, LogIn, UserPlus, Film } from 'lucide-react';
import { calculateHaversineDistance } from '@/lib/utils';

import {
  getStoredTrips,
  saveStoredTrips,
  getStoredVisitedPlaces,
  saveStoredVisitedPlaces,
  getStoredWishlist,
  saveStoredWishlist,
  getStoredChapters,
  saveStoredChapters,
} from '@/lib/storage';

export default function DashboardPage() {
  const [currentUser, setCurrentUser] = useState<FirebaseUser | null>(null);
  const [mobileTab, setMobileTab] = useState<'timeline' | 'map'>('timeline');

  // Trips & State initialized clean
  const [trips, setTrips] = useState<Trip[]>([]);
  const [activeTrip, setActiveTrip] = useState<Trip | null>(null);

  const [chaptersMap, setChaptersMap] = useState<Record<string, TimelineChapter[]>>({});
  const [visitedPlacesMap, setVisitedPlacesMap] = useState<Record<string, VisitedPlace[]>>({});
  const [wishlistItems, setWishlistItems] = useState<WishlistItem[]>([]);

  const activeChapters = activeTrip ? chaptersMap[activeTrip.id] || [] : [];
  const activeVisitedPlaces = activeTrip ? visitedPlacesMap[activeTrip.id] || [] : [];

  const [selectedPlaceId, setSelectedPlaceId] = useState<string | null>(null);
  const [activeDayFilter, setActiveDayFilter] = useState<number | 'all'>('all');

  // Modals & Drawers state
  const [isWishlistOpen, setIsWishlistOpen] = useState(false);
  const [isPhotoUploaderOpen, setIsPhotoUploaderOpen] = useState(false);
  const [isAddVisitModalOpen, setIsAddVisitModalOpen] = useState(false);
  const [isCreateTripModalOpen, setIsCreateTripModalOpen] = useState(false);
  const [isAuthModalOpen, setIsAuthModalOpen] = useState(false);
  const [isOccasionModalOpen, setIsOccasionModalOpen] = useState(false);

  // AI Suite States
  const [isMenuScannerOpen, setIsMenuScannerOpen] = useState(false);
  const [isItineraryPlannerOpen, setIsItineraryPlannerOpen] = useState(false);
  const [visualSearchPhotoUrl, setVisualSearchPhotoUrl] = useState<string | null>(null);
  const [socialCaptionPlace, setSocialCaptionPlace] = useState<VisitedPlace | null>(null);

  const [isGeneratingReel, setIsGeneratingReel] = useState(false);
  const [activeReelData, setActiveReelData] = useState<ReelData | null>(null);
  const [targetChapterId, setTargetChapterId] = useState<string | undefined>(undefined);
  const [pendingAction, setPendingAction] = useState<'create_trip' | 'import_photos' | null>(null);

  // Handle adding Decoded Dish to Current Log
  const handleAddDishToVisitFromMenu = (dish: DecodedDish) => {
    setIsMenuScannerOpen(false);
    setIsAddVisitModalOpen(true);
  };

  // Handle applying generated itinerary to trip chapters
  const handleApplyItineraryToTrip = (itinerary: ItineraryDay[]) => {
    if (!activeTrip) return;
    const newChapters: TimelineChapter[] = itinerary.map((day) => ({
      id: `chap_${activeTrip.id}_d${day.dayNumber}`,
      tripId: activeTrip.id,
      dayNumber: day.dayNumber,
      date: activeTrip.startDate,
      title: day.title,
      notes: `Generated by AI Itinerary Optimizer with ${day.schedule.length} stops.`,
    }));

    setChaptersMap((prev) => ({
      ...prev,
      [activeTrip.id]: newChapters,
    }));

    if (currentUser?.uid) {
      newChapters.forEach((c) => saveChapterToFirestore(currentUser.uid, c));
    }
  };

  const handleStartTripClick = () => {
    if (!currentUser) {
      setPendingAction('create_trip');
      setIsAuthModalOpen(true);
    } else {
      setIsCreateTripModalOpen(true);
    }
  };

  const handleImportPhotosClick = () => {
    if (!currentUser) {
      setPendingAction('import_photos');
      setIsAuthModalOpen(true);
    } else {
      setIsPhotoUploaderOpen(true);
    }
  };

  // Generate Occasion-Based AI Story Reel
  const handleGenerateOccasionReel = async (occasionPrompt: string) => {
    setIsGeneratingReel(true);
    try {
      const res = await fetch('/api/generate-reel', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          tripSlug: activeTrip?.slug || 'tokyo-culinary-odyssey',
          occasionPrompt,
          customPlaces: activeVisitedPlaces,
        }),
      });

      const data = await res.json();
      if (data.success && data.reel) {
        setActiveReelData(data.reel);
        setIsOccasionModalOpen(false);
      }
    } catch (err) {
      console.error('Error generating AI occasion reel:', err);
    } finally {
      setIsGeneratingReel(false);
    }
  };

  // Subscribe to auth changes
  useEffect(() => {
    const unsubscribe = subscribeToAuthChanges((user) => {
      setCurrentUser(user);
    });
    return () => unsubscribe();
  }, []);

  // Sync user profile & user data with Firestore when authenticated
  useEffect(() => {
    if (!currentUser?.uid) {
      // Clear memory & local state on sign out so no data leaks
      setTrips([]);
      setActiveTrip(null);
      setVisitedPlacesMap({});
      setChaptersMap({});
      setWishlistItems([]);
      return;
    }

    // Auto-provision or update user profile document in Firestore users collection
    syncUserProfileToFirestore(currentUser);

    // Fetch ONLY data belonging to currentUser.uid
    fetchUserDataFromFirestore(currentUser.uid).then((fsData) => {
      setTrips(fsData.trips);
      setActiveTrip((prev) => {
        const found = fsData.trips.find((t) => t.id === prev?.id);
        return found || fsData.trips[0] || null;
      });
      setVisitedPlacesMap(fsData.visitedPlacesMap);
      setChaptersMap(fsData.chaptersMap);
      setWishlistItems(fsData.wishlistItems);

      saveStoredTrips(fsData.trips, currentUser.uid);
      saveStoredVisitedPlaces(fsData.visitedPlacesMap, currentUser.uid);
      saveStoredChapters(fsData.chaptersMap, currentUser.uid);
      saveStoredWishlist(fsData.wishlistItems, currentUser.uid);
    });
  }, [currentUser]);

  // Save trips state updates to user-scoped storage
  useEffect(() => {
    if (currentUser?.uid && trips.length > 0) {
      saveStoredTrips(trips, currentUser.uid);
    }
  }, [trips, currentUser]);

  // Save visited places state updates to user-scoped storage
  useEffect(() => {
    if (currentUser?.uid) {
      saveStoredVisitedPlaces(visitedPlacesMap, currentUser.uid);
    }
  }, [visitedPlacesMap, currentUser]);

  // Save wishlist state updates to user-scoped storage
  useEffect(() => {
    if (currentUser?.uid) {
      saveStoredWishlist(wishlistItems, currentUser.uid);
    }
  }, [wishlistItems, currentUser]);

  // Save chapters state updates to user-scoped storage
  useEffect(() => {
    if (currentUser?.uid) {
      saveStoredChapters(chaptersMap, currentUser.uid);
    }
  }, [chaptersMap, currentUser]);

  // Handle creating a new trip or hometown food journal
  const handleCreateTrip = (newTrip: Trip) => {
    if (!currentUser?.uid) {
      setIsAuthModalOpen(true);
      return;
    }
    const finalTrip = { ...newTrip, userId: currentUser.uid };
    const isHometown = finalTrip.categoryType === 'hometown_log' || finalTrip.isHometown;
    const defaultChapter: TimelineChapter = {
      id: `chap_${finalTrip.id}_d1`,
      tripId: finalTrip.id,
      dayNumber: 1,
      date: finalTrip.startDate,
      title: isHometown ? 'Local Dining & Neighborhood Eats' : 'Day 1: Culinary Discoveries',
      notes: isHometown ? 'Favorite local restaurants, cafés, and hometown tasting notes.' : 'First day exploring local tasting spots and flavors.',
    };

    setTrips((prev) => [finalTrip, ...prev]);
    setActiveTrip(finalTrip);
    setChaptersMap((prev) => ({
      ...prev,
      [finalTrip.id]: [defaultChapter],
    }));
    setVisitedPlacesMap((prev) => ({
      ...prev,
      [finalTrip.id]: [],
    }));

    saveTripToFirestore(currentUser.uid, finalTrip);
    saveChapterToFirestore(currentUser.uid, defaultChapter);
  };

  // Select active trip
  const handleSelectTrip = (trip: Trip) => {
    setActiveTrip(trip);
    setSelectedPlaceId(null);
    setActiveDayFilter('all');
  };

  // Convert Wishlist item into a Visited Place
  const handleConvertToVisited = (item: WishlistItem) => {
    if (!currentUser?.uid) {
      setIsAuthModalOpen(true);
      return;
    }
    if (!activeTrip) return;

    const targetChapter = activeChapters[0] || {
      id: `chap_${activeTrip.id}_d1`,
      tripId: activeTrip.id,
      dayNumber: 1,
      date: activeTrip.startDate,
      title: 'Day 1: Culinary Exploration',
    };

    const newVisitedPlace: VisitedPlace = {
      id: `vp_${Date.now()}`,
      tripId: activeTrip.id,
      chapterId: targetChapter.id,
      placeId: item.placeId,
      name: item.name,
      address: item.address,
      lat: item.lat,
      lng: item.lng,
      visitTime: new Date().toISOString(),
      photoUrls: item.photoUrl
        ? [item.photoUrl]
        : ['https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80'],
      dishTags: [item.category, 'Must Try Spot'],
      rating: 5,
      tastingNotes: item.notes || `Converted from Wishlist bookmark!`,
      category: item.category,
      priceLevel: 2,
      isHometown: activeTrip.categoryType === 'hometown_log' || activeTrip.isHometown,
    };

    setVisitedPlacesMap((prev) => ({
      ...prev,
      [activeTrip.id]: [...(prev[activeTrip.id] || []), newVisitedPlace],
    }));

    setWishlistItems((prev) => prev.filter((w) => w.id !== item.id));
    setSelectedPlaceId(newVisitedPlace.id);

    saveVisitedPlaceToFirestore(currentUser.uid, newVisitedPlace);
    deleteWishlistItemFromFirestore(item.id);
  };

  // Add Wishlist item
  const handleAddWishlistItem = (item: Partial<WishlistItem>) => {
    if (!currentUser?.uid) {
      setIsAuthModalOpen(true);
      return;
    }
    const newItem: WishlistItem = {
      id: `wish_${Date.now()}`,
      userId: currentUser.uid,
      tripId: activeTrip?.id,
      placeId: item.placeId || `p_${Date.now()}`,
      name: item.name || 'Unnamed Spot',
      address: item.address || 'Dining Destination',
      lat: item.lat || 35.6875,
      lng: item.lng || 139.6972,
      notes: item.notes || '',
      category: item.category || 'Restaurant',
      priority: item.priority || 'must-try',
      createdAt: new Date().toISOString(),
      photoUrl: item.photoUrl,
    };
    setWishlistItems((prev) => [newItem, ...prev]);

    saveWishlistItemToFirestore(currentUser.uid, newItem);
  };

  // Remove Wishlist item
  const handleRemoveWishlistItem = (id: string) => {
    setWishlistItems((prev) => prev.filter((w) => w.id !== id));
    if (currentUser?.uid) {
      deleteWishlistItemFromFirestore(id);
    }
  };

  // Save manually added Visit (Auto-creates Hometown Journal if no trip is selected)
  const handleSaveVisit = (visit: Partial<VisitedPlace>) => {
    if (!currentUser?.uid) {
      setIsAuthModalOpen(true);
      return;
    }

    let currentTrip = trips.find((t) => t.id === visit.tripId) || activeTrip;
    let targetChapterId = visit.chapterId;

    if (!currentTrip) {
      // Auto-create default Hometown Food Journal
      currentTrip = {
        id: `hometown_${Date.now()}`,
        userId: currentUser.uid,
        title: 'My Hometown Food Journal',
        slug: 'hometown-food-journal',
        destination: 'My Home City',
        startDate: new Date().toISOString().split('T')[0],
        endDate: 'Ongoing',
        coverUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
        summary: 'Everyday local restaurant visits, tasting notes, and neighborhood dining stories.',
        visibility: 'public',
        createdAt: new Date().toISOString(),
        categoryType: 'hometown_log',
        isHometown: true,
      };

      const defaultChapter: TimelineChapter = {
        id: `chap_${currentTrip.id}_local`,
        tripId: currentTrip.id,
        dayNumber: 1,
        date: new Date().toISOString().split('T')[0],
        title: 'Local Restaurant Stories',
        notes: 'Hometown dining spots & tasting notes.',
      };

      setTrips((prev) => [currentTrip!, ...prev]);
      setActiveTrip(currentTrip);
      setChaptersMap((prev) => ({
        ...prev,
        [currentTrip!.id]: [defaultChapter],
      }));

      targetChapterId = defaultChapter.id;

      saveTripToFirestore(currentUser.uid, currentTrip);
      saveChapterToFirestore(currentUser.uid, defaultChapter);
    }

    const newPlace: VisitedPlace = {
      id: `vp_${Date.now()}`,
      tripId: currentTrip.id,
      chapterId: targetChapterId || activeChapters[0]?.id || `chap_${currentTrip.id}_d1`,
      placeId: visit.placeId || `p_${Date.now()}`,
      name: visit.name || 'Culinary Spot',
      address: visit.address || 'Dining Destination',
      lat: visit.lat || 35.6875,
      lng: visit.lng || 139.6972,
      visitTime: visit.visitTime || new Date().toISOString(),
      photoUrls: visit.photoUrls || [],
      dishTags: visit.dishTags || ['Tasty'],
      rating: visit.rating || 5,
      tastingNotes: visit.tastingNotes || '',
      priceLevel: visit.priceLevel || 2,
      category: visit.category || 'Ramen',
      recommendedDish: visit.recommendedDish,
      isHometown: visit.isHometown || currentTrip.categoryType === 'hometown_log' || currentTrip.isHometown,
    };

    setVisitedPlacesMap((prev) => ({
      ...prev,
      [currentTrip!.id]: [...(prev[currentTrip!.id] || []), newPlace],
    }));

    if (currentTrip.id === activeTrip?.id) {
      setSelectedPlaceId(newPlace.id);
    }

    saveVisitedPlaceToFirestore(currentUser.uid, newPlace);
  };

  // Delete Visit
  const handleDeletePlace = (placeId: string) => {
    if (!activeTrip) return;
    setVisitedPlacesMap((prev) => ({
      ...prev,
      [activeTrip.id]: (prev[activeTrip.id] || []).filter((p) => p.id !== placeId),
    }));

    if (currentUser?.uid) {
      deleteVisitedPlaceFromFirestore(placeId);
    }
  };

  // Import AI Processed Chapters
  const handleImportAIChapters = (aiChapters: AIProcessedPhotoGroup[]) => {
    if (!currentUser?.uid) {
      setIsAuthModalOpen(true);
      return;
    }

    if (!activeTrip) {
      // Auto create a trip for imported photos
      const autoTrip: Trip = {
        id: `trip_${Date.now()}`,
        userId: currentUser.uid,
        title: aiChapters[0]?.suggestedChapterTitle || 'New Food Journey',
        slug: `food-journey-${Date.now()}`,
        destination: 'Culinary Destination',
        startDate: aiChapters[0]?.date || new Date().toISOString().split('T')[0],
        endDate: new Date().toISOString().split('T')[0],
        coverUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80',
        summary: 'AI Generated culinary travel log from photo import.',
        visibility: 'public',
        createdAt: new Date().toISOString(),
      };
      setTrips([autoTrip]);
      setActiveTrip(autoTrip);
      
      const newChapters: TimelineChapter[] = [];
      const newPlaces: VisitedPlace[] = [];

      aiChapters.forEach((ac, idx) => {
        const chapId = `chap_ai_${Date.now()}_${idx}`;
        newChapters.push({
          id: chapId,
          tripId: autoTrip.id,
          dayNumber: idx + 1,
          date: ac.date,
          title: ac.suggestedChapterTitle,
        });

        ac.places.forEach((p, pIdx) => {
          newPlaces.push({
            id: `vp_ai_${Date.now()}_${idx}_${pIdx}`,
            tripId: autoTrip.id,
            chapterId: chapId,
            placeId: `place_ai_${Date.now()}_${pIdx}`,
            name: p.suggestedVenueName,
            address: 'Dining Spot',
            lat: p.lat || 35.6875 + pIdx * 0.005,
            lng: p.lng || 139.6972 + pIdx * 0.005,
            visitTime: p.visitTime,
            photoUrls: p.photoUrls,
            dishTags: p.detectedDishes,
            rating: p.suggestedRating,
            tastingNotes: p.suggestedTastingNotes,
            category: p.suggestedCategory,
          });
        });
      });

      setChaptersMap({ [autoTrip.id]: newChapters });
      setVisitedPlacesMap({ [autoTrip.id]: newPlaces });

      saveTripToFirestore(currentUser.uid, autoTrip);
      newChapters.forEach((c) => saveChapterToFirestore(currentUser.uid, c));
      newPlaces.forEach((vp) => saveVisitedPlaceToFirestore(currentUser.uid, vp));
      return;
    }

    const newChapters: TimelineChapter[] = [];
    const newPlaces: VisitedPlace[] = [];

    aiChapters.forEach((ac, idx) => {
      const chapId = `chap_ai_${Date.now()}_${idx}`;
      const dayNum = activeChapters.length + idx + 1;

      newChapters.push({
        id: chapId,
        tripId: activeTrip.id,
        dayNumber: dayNum,
        date: ac.date,
        title: ac.suggestedChapterTitle,
        notes: `AI Generated timeline from photo batch import`,
      });

      ac.places.forEach((p, pIdx) => {
        newPlaces.push({
          id: `vp_ai_${Date.now()}_${idx}_${pIdx}`,
          tripId: activeTrip.id,
          chapterId: chapId,
          placeId: `place_ai_${Date.now()}_${pIdx}`,
          name: p.suggestedVenueName,
          address: 'Dining Spot',
          lat: p.lat || 35.6875 + pIdx * 0.005,
          lng: p.lng || 139.6972 + pIdx * 0.005,
          visitTime: p.visitTime,
          photoUrls: p.photoUrls,
          dishTags: p.detectedDishes,
          rating: p.suggestedRating,
          tastingNotes: p.suggestedTastingNotes,
          category: p.suggestedCategory,
          priceLevel: 2,
        });
      });
    });

    setChaptersMap((prev) => ({
      ...prev,
      [activeTrip.id]: [...(prev[activeTrip.id] || []), ...newChapters],
    }));

    setVisitedPlacesMap((prev) => ({
      ...prev,
      [activeTrip.id]: [...(prev[activeTrip.id] || []), ...newPlaces],
    }));

    if (currentUser?.uid) {
      newChapters.forEach((c) => saveChapterToFirestore(currentUser.uid, c));
      newPlaces.forEach((vp) => saveVisitedPlaceToFirestore(currentUser.uid, vp));
    }
  };

  const totalKmTraveled = activeVisitedPlaces.reduce((acc, curr, idx, arr) => {
    if (idx === 0) return 0;
    const prev = arr[idx - 1];
    return acc + calculateHaversineDistance(prev.lat, prev.lng, curr.lat, curr.lng);
  }, 0);

  return (
    <div className="min-h-screen bg-[#FDF8F0] text-[#025259] flex flex-col font-sans selection:bg-[#ff947a] selection:text-[#025259]">
      
      {/* Top Navbar Header */}
      <Navbar
        trips={trips}
        activeTrip={activeTrip}
        onSelectTrip={handleSelectTrip}
        onOpenCreateTrip={handleStartTripClick}
        onOpenWishlist={() => setIsWishlistOpen(false || true)}
        onOpenPhotoUploader={handleImportPhotosClick}
        onOpenMenuScanner={() => setIsMenuScannerOpen(true)}
        onOpenItineraryPlanner={() => setIsItineraryPlannerOpen(true)}
        onOpenAuth={() => setIsAuthModalOpen(true)}
        currentUser={currentUser}
        onSignOut={() => logoutUser()}
        visitedCount={activeVisitedPlaces.length}
        wishlistCount={wishlistItems.length}
      />

      {/* Main Content Dashboard */}
      <main className="flex-1 mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8 py-6 space-y-6">
        
        {/* Onboarding View if no trip exists */}
        {!activeTrip ? (
          <div className="rounded-3xl border border-[#025259]/20 bg-[#FFFFFF] p-8 sm:p-12 shadow-xl text-center space-y-6 max-w-3xl mx-auto my-8">
            <div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-[#ff947a] text-[#025259] shadow-md">
              <Compass className="h-9 w-9 stroke-[2.5]" />
            </div>
            
            <div className="space-y-2">
              <h1 className="text-2xl sm:text-3xl font-serif font-bold text-[#025259]">
                {currentUser ? `Welcome, ${currentUser.displayName || 'Food Explorer'}!` : 'Welcome to ForkTrail'}
              </h1>
              <p className="text-sm text-stone-600 max-w-md mx-auto leading-relaxed">
                {currentUser
                  ? 'Your clean culinary travel diary. Start a new trip or hometown food journal, import EXIF photos, and log dining spots.'
                  : 'Your clean culinary travel diary. Please sign in or create an account to start logging food trips, importing EXIF photos, and syncing across mobile & desktop.'}
              </p>
            </div>

            {!currentUser ? (
              <div className="flex justify-center pt-2">
                <button
                  onClick={() => setIsAuthModalOpen(true)}
                  className="flex items-center gap-2.5 rounded-xl bg-[#ff947a] px-8 py-3.5 text-sm font-bold text-[#025259] hover:bg-[#f08368] transition shadow-md hover:scale-102"
                >
                  <LogIn className="h-5 w-5" />
                  Sign In / Create Account
                </button>
              </div>
            ) : (
              <div className="flex flex-wrap items-center justify-center gap-3 pt-2">
                <button
                  onClick={() => setIsCreateTripModalOpen(true)}
                  className="flex items-center gap-2 rounded-xl bg-[#ff947a] px-6 py-3 text-sm font-bold text-[#025259] hover:bg-[#f08368] transition shadow-md"
                >
                  <Plus className="h-5 w-5" />
                  Start Food Log or Trip
                </button>

                <button
                  onClick={() => setIsPhotoUploaderOpen(true)}
                  className="flex items-center gap-2 rounded-xl border border-[#025259]/20 bg-[#FAF3E7] px-5 py-3 text-sm font-bold text-[#025259] hover:bg-[#FDF8F0] transition shadow-sm"
                >
                  <Sparkles className="h-4 w-4 text-[#ff947a]" />
                  Batch Import EXIF Photos
                </button>
              </div>
            )}
          </div>
        ) : (
          /* Active Trip / Log Hero Header Bar */
          <div className="relative rounded-3xl overflow-hidden border border-[#025259]/20 bg-[#025259] text-white shadow-xl p-6 sm:p-8">
            <div className="absolute inset-0 opacity-20">
              <img
                src={activeTrip.coverUrl}
                alt={activeTrip.title}
                className="h-full w-full object-cover filter blur-sm scale-105"
              />
              <div className="absolute inset-0 bg-gradient-to-r from-[#025259] via-[#025259]/90 to-transparent" />
            </div>

            <div className="relative z-10 flex flex-col lg:flex-row lg:items-center justify-between gap-6">
              <div className="space-y-2 max-w-2xl">
                <div className="flex flex-wrap items-center gap-2 text-xs">
                  <span className="rounded-full bg-[#ff947a] px-3 py-1 font-bold text-[#025259] shadow-sm">
                    {activeTrip.categoryType === 'hometown_log' || activeTrip.isHometown ? '🏠 Hometown Log' : '✈️ Travel Trip'} • {activeTrip.destination}
                  </span>
                  <span className="flex items-center gap-1.5 text-[#FDF8F0] bg-[#013b40]/80 px-3 py-1 rounded-full border border-[#03717b]">
                    <Calendar className="h-3.5 w-3.5 text-[#E3A857]" />
                    {activeTrip.startDate} — {activeTrip.endDate}
                  </span>
                </div>

                <h1 className="text-2xl sm:text-4xl font-serif font-bold text-white tracking-tight">
                  {activeTrip.title}
                </h1>

                <p className="text-xs sm:text-sm text-[#FAF3E7] leading-relaxed">
                  {activeTrip.summary}
                </p>
              </div>

              {/* Quick Metrics Bar */}
              <div className="flex items-center gap-4 bg-[#013b40]/90 backdrop-blur border border-[#03717b] p-4 rounded-2xl shrink-0 text-center shadow-md">
                <div>
                  <span className="block text-xl font-bold text-[#ff947a]">{activeVisitedPlaces.length}</span>
                  <span className="text-[10px] text-[#FAF3E7] uppercase tracking-wider font-semibold">Spots Logged</span>
                </div>
                <div className="h-8 w-[1px] bg-[#03717b]" />
                <div>
                  <span className="block text-xl font-bold text-[#E3A857]">{wishlistItems.length}</span>
                  <span className="text-[10px] text-[#FAF3E7] uppercase tracking-wider font-semibold">Wishlist</span>
                </div>
                <div className="h-8 w-[1px] bg-[#03717b]" />
                <div>
                  <span className="block text-xl font-bold text-white">{totalKmTraveled} km</span>
                  <span className="text-[10px] text-[#FAF3E7] uppercase tracking-wider font-semibold">Trail Route</span>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Dashboard Split View: Interactive Map (Left) + Daily Timeline (Right) */}
        {activeTrip && (
          <div className="space-y-4">
            
            {/* Mobile View Switcher (< lg screens) */}
            <div className="flex lg:hidden items-center justify-center p-1 bg-[#FFFFFF] rounded-2xl border border-[#025259]/15 shadow-sm">
              <button
                type="button"
                onClick={() => setMobileTab('timeline')}
                className={`flex-1 py-2 px-4 rounded-xl text-xs font-bold transition flex items-center justify-center gap-2 ${
                  mobileTab === 'timeline'
                    ? 'bg-[#ff947a] text-[#025259] shadow-sm'
                    : 'text-stone-600 hover:text-[#025259]'
                }`}
              >
                <Layers className="h-4 w-4" />
                <span>Timeline Diary</span>
              </button>
              <button
                type="button"
                onClick={() => setMobileTab('map')}
                className={`flex-1 py-2 px-4 rounded-xl text-xs font-bold transition flex items-center justify-center gap-2 ${
                  mobileTab === 'map'
                    ? 'bg-[#ff947a] text-[#025259] shadow-sm'
                    : 'text-stone-600 hover:text-[#025259]'
                }`}
              >
                <MapPin className="h-4 w-4" />
                <span>Interactive Map</span>
              </button>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start pb-20 md:pb-8">
              
              {/* Left Column: Interactive Map Component */}
              <div
                className={`lg:col-span-6 h-[460px] sm:h-[550px] lg:h-[750px] lg:sticky lg:top-20 ${
                  mobileTab === 'map' ? 'block' : 'hidden lg:block'
                }`}
              >
                <MapView
                  visitedPlaces={activeVisitedPlaces}
                  wishlistItems={wishlistItems}
                  chapters={activeChapters}
                  selectedPlaceId={selectedPlaceId}
                  onSelectPlace={(place) => place && setSelectedPlaceId(place.id)}
                  onConvertToVisited={handleConvertToVisited}
                  activeDayFilter={activeDayFilter}
                  onSelectDayFilter={(day) => setActiveDayFilter(day)}
                />
              </div>

              {/* Right Column: Timeline Chapters & Food Log */}
              <div
                className={`lg:col-span-6 space-y-6 ${
                  mobileTab === 'timeline' ? 'block' : 'hidden lg:block'
                }`}
              >
                
                <div className="flex flex-wrap items-center justify-between gap-3 bg-[#FFFFFF] p-4 rounded-2xl border border-[#025259]/15 shadow-sm">
                  <div className="flex items-center gap-2">
                    <Layers className="h-5 w-5 text-[#ff947a]" />
                    <h2 className="font-serif font-bold text-lg text-[#025259]">
                      {activeTrip.categoryType === 'hometown_log' || activeTrip.isHometown ? 'Hometown Food Journal' : 'Daily Food Diary'}
                    </h2>
                  </div>

                  <div className="flex items-center gap-2">
                    <button
                      onClick={() => setIsOccasionModalOpen(true)}
                      className="flex items-center gap-1.5 rounded-lg border border-[#025259]/20 bg-[#FAF3E7] px-3 py-1.5 text-xs font-bold text-[#025259] hover:bg-[#FDF8F0] transition shadow-sm"
                    >
                      <Sparkles className="h-4 w-4 text-[#ff947a]" />
                      AI Occasion Story
                    </button>

                    <button
                      onClick={() => {
                        setTargetChapterId(undefined);
                        setIsAddVisitModalOpen(true);
                      }}
                      className="flex items-center gap-1.5 rounded-lg bg-[#ff947a] border border-[#ff947a] px-3 py-1.5 text-xs font-bold text-[#025259] hover:bg-[#f08368] transition shadow-sm"
                    >
                      <Plus className="h-4 w-4" />
                      Log Visit
                    </button>
                  </div>
                </div>

                {/* Timeline View Component */}
                <TimelineView
                  chapters={activeChapters}
                  visitedPlaces={activeVisitedPlaces}
                  selectedPlaceId={selectedPlaceId}
                  onSelectPlace={(place) => setSelectedPlaceId(place.id)}
                  onOpenAddModal={(chapId) => {
                    setTargetChapterId(chapId);
                    setIsAddVisitModalOpen(true);
                  }}
                  onDeletePlace={handleDeletePlace}
                  onOpenVisualSearch={(url) => setVisualSearchPhotoUrl(url)}
                  onOpenSocialCaptions={(place) => setSocialCaptionPlace(place)}
                />

              </div>

            </div>
          </div>
        )}

      </main>

      {/* Modals & Drawers */}
      <WishlistDrawer
        isOpen={isWishlistOpen}
        onClose={() => setIsWishlistOpen(false)}
        wishlistItems={wishlistItems}
        onAddWishlistItem={handleAddWishlistItem}
        onConvertToVisited={handleConvertToVisited}
        onRemoveWishlistItem={handleRemoveWishlistItem}
        onOpenItineraryPlanner={() => {
          setIsWishlistOpen(false);
          setIsItineraryPlannerOpen(true);
        }}
      />

      <MenuScannerModal
        isOpen={isMenuScannerOpen}
        onClose={() => setIsMenuScannerOpen(false)}
        onAddDishToVisit={handleAddDishToVisitFromMenu}
        onAddDishToWishlist={(dish) => {
          handleAddWishlistItem({
            name: dish.translatedName,
            category: 'Menu Specialty',
            notes: `Extracted from menu: ${dish.description}. Price: ${dish.price}`,
            priority: 'must-try',
          });
        }}
      />

      <ItineraryPlanner
        isOpen={isItineraryPlannerOpen}
        onClose={() => setIsItineraryPlannerOpen(false)}
        wishlistItems={wishlistItems}
        visitedPlaces={activeVisitedPlaces}
        destination={activeTrip?.destination || 'Tokyo'}
        onApplyItineraryToTrip={handleApplyItineraryToTrip}
      />

      <VisualDishFinder
        isOpen={Boolean(visualSearchPhotoUrl)}
        onClose={() => setVisualSearchPhotoUrl(null)}
        photoUrl={visualSearchPhotoUrl || ''}
        userLat={activeVisitedPlaces[0]?.lat || 35.6875}
        userLng={activeVisitedPlaces[0]?.lng || 139.6972}
        onAddWishlistItem={handleAddWishlistItem}
      />

      <SocialCaptionModal
        isOpen={Boolean(socialCaptionPlace)}
        onClose={() => setSocialCaptionPlace(null)}
        place={socialCaptionPlace}
        destinationCity={activeTrip?.destination || 'Tokyo'}
      />

      <PhotoUploader
        isOpen={isPhotoUploaderOpen}
        onClose={() => setIsPhotoUploaderOpen(false)}
        onImportChapters={handleImportAIChapters}
        userId={currentUser?.uid}
      />

      <OccasionPromptModal
        isOpen={isOccasionModalOpen}
        onClose={() => setIsOccasionModalOpen(false)}
        onGenerate={handleGenerateOccasionReel}
        isGenerating={isGeneratingReel}
      />

      {activeReelData && (
        <ReelViewer
          tripTitle={activeTrip?.title || 'Culinary Experience'}
          reelData={activeReelData}
          onClose={() => setActiveReelData(null)}
          onOpenOccasionModal={() => setIsOccasionModalOpen(true)}
        />
      )}

      <AddVisitModal
        isOpen={isAddVisitModalOpen}
        onClose={() => setIsAddVisitModalOpen(false)}
        chapters={activeChapters}
        defaultChapterId={targetChapterId}
        onSaveVisit={handleSaveVisit}
        trips={trips}
        activeTrip={activeTrip}
        onSelectTrip={handleSelectTrip}
        isHometown={activeTrip?.categoryType === 'hometown_log' || activeTrip?.isHometown}
        userId={currentUser?.uid}
      />

      <CreateTripModal
        isOpen={isCreateTripModalOpen}
        onClose={() => setIsCreateTripModalOpen(false)}
        onCreateTrip={handleCreateTrip}
        userId={currentUser?.uid}
      />

      <AuthModal
        isOpen={isAuthModalOpen}
        onClose={() => {
          setIsAuthModalOpen(false);
          setPendingAction(null);
        }}
        onSuccess={(user) => {
          setCurrentUser(user);
          if (pendingAction === 'create_trip') {
            setIsCreateTripModalOpen(true);
          } else if (pendingAction === 'import_photos') {
            setIsPhotoUploaderOpen(true);
          }
          setPendingAction(null);
        }}
      />

      {/* Footer (Hidden on Mobile screens, visible on md and above) */}
      <footer className="hidden md:block mt-12 border-t border-[#013b40] bg-[#025259] py-8 text-center text-xs text-[#FAF3E7]">
        <div className="mx-auto max-w-7xl px-4 flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="relative flex h-8 w-8 items-center justify-center rounded-lg bg-[#FAF3E7] p-1 shadow-sm">
              <Image src="/logo-mark.png" alt="ForkTrail Logo" width={28} height={28} className="h-full w-full object-contain" />
            </div>
            <div className="text-left">
              <span className="font-serif font-bold text-white text-sm block leading-tight">ForkTrail</span>
              <span className="text-[10px] uppercase tracking-widest text-[#E3A857] font-semibold block">Your Culinary Journey</span>
            </div>
          </div>
          <p>© {new Date().getFullYear()} ForkTrail. Built for foodies, travelers & culinary storytellers.</p>
        </div>
      </footer>

      <MobileNavigation
        onOpenPhotoUploader={handleImportPhotosClick}
        onOpenWishlist={() => setIsWishlistOpen(true)}
        wishlistCount={wishlistItems.length}
      />
    </div>
  );
}
